# Project information
site_name: OpenTechMind
site_url: https://OpenTechMind.com/
site_author: OpenTechMind
site_description: This is the website for OpenTechMind

# Copyright
copyright: >-
  Copyright &copy; All rights reserved. 2024 <br>
  TechxArtisan Limited | OpenTechMind<br>
  <a href="">Home</a> |
  <a href="#__consent">Cookie</a> |
  <a href="mailto:info@OpenTechMind.com">Email Us</a>

# extra_css:
#   - assets/stylesheets/extra.css
extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/custom_style.css
  - assets/stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  - assets/stylesheets/signup_form.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.svg
  favicon: images/favicon.svg
  features:
  #  - navigation.tabs
   - navigation.sections
  #  - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
   - content.tabs.link
  
  # palette:
  #   scheme: default
  #   primary: black
  #   accent: custom

  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
        
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: techxartisan
      link: https://www.techxartisan.com
    - icon: fontawesome/solid/envelope
      link: mailto:info@OpenTechMind.com

  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to enhance quality of docs content, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-VEF8HJFKLC

markdown_extensions:
  # Enables tables
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
              custom_icons:
                - overrides/.icons
  - toc:
      permalink: ¶
      toc_depth: 2

plugins:
  - glightbox
  - search
  - redirects:
      redirect_maps:
        'x.md': 'https://x.com/OpenTechMind'
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - Home: index.md