authors:
  OpenTechMind:
    name: OpenTechMind
    description: A creative tech studio developing practical hardware and offering consultancy to help you work smarter and collaborate better.
    avatar: /images/otom.jpg